### PR TITLE
CGLGetShareGroup added

### PR DESCRIPTION
**Pull request by Kerosene2000**
This change is [Reviewable](https://reviewable.io/reviews/servo/cgl-rs/19)

### CODE REVIEW

**Comment by metajack** [comment]
Thanks!

**Comment by emilio** [comment]
Whoops, arrived late, sorry @metajack

**Comment by Kerosene2000** [comment]
No version bumping ?

**Comment by emilio** [comment]
I'll do it right now

**Comment by emilio** [comment]
Published as 0.1.5

**Pull request merged**
